baseURL = "https://spasoye.github.io/spas-tech.github.io/"
languageCode = "en-us"
title = "Spas Tech"
theme = "ananke"

relativeURLs = true
canonifyURLs = true

[pagination]
#pagerSize = 3  this is set low for demonstrating with dummy content. Set to a higher number

contentDir = "content"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1  # Lower weight means it appears first

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

[params]
custom_css = ["css/custom.css"]

[params.ananke.social.follow]
networks = [
  "facebook",
  "linkedin"
]

[params.ananke.social.facebook]
username = "patrick.kollitsch"
# profilelink = "https://www.facebook.com/patrick.kollitsch"

[params.ananke.social.linkedin]
username = "patrickkollitsch"

[params.ananke.social.bluesky]
username = "kollitsch.dev"

[params.ananke.social.wikipedia]
username = "Hugo_(software)"