#baseURL = "https://spasoye.github.io/spas-tech.github.io/"
baseURL = "http://spas-tech.hr/"
languageCode = "en-us"
title = "Spas Tech"
theme = "ananke"

relativeURLs = false

markup.goldmark.renderer.unsafe = true

contentDir = "content"

[permalinks]
  about = "/about/"
  contact = "/contact/"

[pagination]
#pagerSize = 3  this is set low for demonstrating with dummy content. Set to a higher number

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1  # Lower weight means it appears first

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

  [[menu.main]]
    name = "Biz Info"
    url = "/business_info/"
    weight = 4

[params]
custom_css = ["css/custom.css"]
