baseURL = "https://yourdomain.com/"
languageCode = "en-us"
title = "Spas Tech"
theme = "ananke"


[menu]
  [[menu.main]]
    name = "About"
    url = "about/about.md"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "projects/projects.md"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "contact/contact.md"
    weight = 3

contentDir = "content"
